// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfBn4FNfb0kKt0_q0B8-8ekSnrx0ZTt1w',
    appId: '1:1058190242127:web:f4a24243aa32dab623953a',
    messagingSenderId: '1058190242127',
    projectId: 'fixitnow-d362a',
    authDomain: 'fixitnow-d362a.firebaseapp.com',
    storageBucket: 'fixitnow-d362a.firebasestorage.app',
    measurementId: 'G-2W7E9VN8Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHIn_MF30uRjT4Xwy_YgRfvTE7hsoKhw',
    appId: '1:1058190242127:android:76ecf04ad90fd5f723953a',
    messagingSenderId: '1058190242127',
    projectId: 'fixitnow-d362a',
    storageBucket: 'fixitnow-d362a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsUHjeuXT6_cHSaxnmGKHraE3184rXFtY',
    appId: '1:1058190242127:ios:1be9bcca406960a423953a',
    messagingSenderId: '1058190242127',
    projectId: 'fixitnow-d362a',
    storageBucket: 'fixitnow-d362a.firebasestorage.app',
    iosBundleId: 'com.example.fixitnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsUHjeuXT6_cHSaxnmGKHraE3184rXFtY',
    appId: '1:1058190242127:ios:1be9bcca406960a423953a',
    messagingSenderId: '1058190242127',
    projectId: 'fixitnow-d362a',
    storageBucket: 'fixitnow-d362a.firebasestorage.app',
    iosBundleId: 'com.example.fixitnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfBn4FNfb0kKt0_q0B8-8ekSnrx0ZTt1w',
    appId: '1:1058190242127:web:b9248c0a244a006a23953a',
    messagingSenderId: '1058190242127',
    projectId: 'fixitnow-d362a',
    authDomain: 'fixitnow-d362a.firebaseapp.com',
    storageBucket: 'fixitnow-d362a.firebasestorage.app',
    measurementId: 'G-2VDN8GQ20L',
  );
}
